REVIEWS = [
 ("Carla Quintana","Local Guide · 16 reviews","2 weeks ago",
  "Eric was great, I was doubtfull at first given he is in high school but the results spoke for themselves this young man is great at what he does, totally recommend for anyone looking for a detailer.", True),
 ("Bruno DiDuca","3 reviews","2 weeks ago",
  "Highly recommenced. He did a marvelous job with attention to every detail. I own a dog my truck was a very challenging job. Eric took the time to make sure everything was perfect when the job was complete. Definitely would use them again.", True),
 ("Victor Ay","1 review · 1 photo","2 weeks ago",
  "Excellent service, I will definitely hire them again", True),
 ("Chris Fremont","2 reviews · 1 photo","2 months ago",
  "Got the full interior and exterior package done by Eric and team, and im impressed, the car looks better than the day I got it. The mats came out incredible. I thought they were beyond saving, and Eric proved me wrong. Carpet, seats, dash, everything got real attention. The exterior is smooth and glossy. Eric also walked me through the maintenance plan, honestly a no-brainer if you want to keep the car looking like this. Thanks, Eric and team 10/10 already booked my next appointment.", False),
 ("Li Anguo","8 reviews · 2 photos","2 months ago",
  "Eric is such a nice guy! Absolutely amazing service. The car looked brand new after the detail — super clean interior, spotless exterior, and great attention to detail. Very professional, friendly, and easy to work with. You can tell they really care about the quality of their work. Highly recommend Eurodetailing if you want your car looking perfect again!", False),
 ("David Atsiliem","1 review · 2 photos","2 months ago",
  "Eric did an excellent job detailing my car. He came fully prepared with all equipment and clearly takes pride in his work. The results were impressive, my car looked showroom inside and out. He also set me up with a maintenance plan, so now it's getting detailed regularly each month, which has been a huge help. Highly recommend his services.", False),
 ("E. Fernando","4 reviews · 2 photos","a month ago", None, False),
 ("Ma Lu","3 reviews · 3 photos","10 months ago",
  "Thank you Eurodetailing/Eric and team for your hard work! My car feels like new again! Getting the carpet, mats, and all the interior clean is so important given the amount of time you spend breathing in your car. Thank you so much for your meticulous work. I 100% recommend their services!", False),
 ("Jean DeBenedictis","1 review","a year ago",
  "Eric and team did a fantastic job on my car. It truly never looked so good. Every detail, inside and out, shines to perfection. They were a pleasure to work with. Highly recommend!", False),
 ("Vincent Forsythe","8 reviews · 3 photos","a year ago",
  "Eric and his team did a full reset of my MDX and I could not believe the results. They carefully detailed every nook, revived all of my black interior plastics and mats. They were perfectionists. Highly recommend!", False),
]
